#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=36
#SBATCH --ntasks-per-node=40
#SBATCH --threads-per-core=1
#SBATCH -A cli@cpu
#SBATCH --hint=nomultithread
#SBATCH -J JOB_
#SBATCH -e zjob.e%j
#SBATCH -o zjob.o%j
#SBATCH --time=6:30:00
#SBATCH --dependency=afterok:772181
#SBATCH --exclusive

cd /gpfswork/rech/cli/rcli002/RUNS/RUN_eNATL36X/eNATL36X-GJMFOR/CTL/PREPARE_FORCING
#./corr_vect.x -m eNATL36X_domain_cfg_v3.3.2.nc -f NAMELISTS_UV/namelist_y2004m01

ATMCONFIG=WRFATL12
ATMCASE=now2
ATMCONFCASE=${ATMCONFIG}-${ATMCASE}
freq=1h

n=0

for f in NAMELISTS_UV/namelist_y*_x ; do
   namroot=$( echo $f | sed -e "s;_x;;" )
   ./corr_vect.x -m eNATL36X_domain_cfg_v3.3.2.nc -f  $namroot &
   n=$(( n + 1 ))
   if [ $n = 36 ] ; then
     wait
     n=0
   fi
done
wait
